name: CI
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm test

  test-types:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
        ts: [4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Install TypeScript Version ${{ matrix.ts }}
        run: pnpm install typescript@${{ matrix.ts }}

      - name: Test Types
        run: pnpm type-check
